--Script básico de criação do banco de dados
CREATE DATABASE SUCOS_VENDAS

-- Criação das tabelas
USE SUCOS_VENDAS
CREATE TABLE [TABELA DE CLIENTES](
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (100),
	[ENDERECO1] [VARCHAR] (150),
	[ENDERECO2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50), 
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
)

CREATE TABLE [TABELA DE VENDEDORES](
	[MATRICULA] [VARCHAR] (5),
	[NOME] [VARCHAR] (100),
	[PERCENTUAL DE COMISSAO] [FLOAT]
)

CREATE TABLE [TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [varchar](20),
	[NOME DO PRODUTO] [varchar](150),
	[EMBALAGEM] [varchar](50),
	[TAMANHO] [varchar](50),
	[SABOR] [varchar](50),
	[PRECO DE LISTA] [smallmoney]
)