-- Alterando a tabela já criada e adicionando chave primária 
ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR (20) NOT NULL 

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK TABELA DE PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

--

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

-- Adicionando chave estrangeira 